name: radio_app
description: "App de radio con múltiples estaciones"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Compartir
  share_plus: ^10.0.2

  # Información de versión
  package_info_plus: ^8.0.0

  # Reproductor
  just_audio: ^0.9.39
  audio_session: ^0.1.18

  # Just Audio Background (versión estable recomendada para Android 33+)
  just_audio_background: ^0.0.1-beta.16

  # Streams
  rxdart: ^0.27.7

  # Estado
  provider: ^6.1.2
  path_provider: ^2.1.2

  # UI
  carousel_slider: ^5.0.0
  url_launcher: ^6.3.1
  google_fonts: ^6.2.1
  shared_preferences: ^2.5.3
  font_awesome_flutter: ^10.12.0

dev_dependencies:
  flutter_launcher_icons: ^0.10.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
